// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    public partial class AmsCamposAdicionaisRelColheita
    {
        public int IdrelColheita { get; set; }
        public int Sequencia { get; set; }
        public int CodAtributo { get; set; }
        public string Valor { get; set; }
        public string ValorRtf { get; set; }
        public byte[] ControlTs { get; set; }

        public virtual AmsRelColheitas IdrelColheitaNavigation { get; set; }
    }
}