// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    public partial class AmsColheitas
    {
        public AmsColheitas()
        {
            AmsCamposAdicionaisColheitas = new HashSet<AmsCamposAdicionaisColheitas>();
            AmsColheitaEtiquetas = new HashSet<AmsColheitaEtiquetas>();
            AmsColheitaParametros = new HashSet<AmsColheitaParametros>();
        }

        public int IdrelColheita { get; set; }
        public int Idcolheita { get; set; }
        public int? CodProgramacao { get; set; }
        public string CodPonto { get; set; }
        public int? CodTipoColheita { get; set; }
        public string DescrColheita { get; set; }
        public int? CodAmostra { get; set; }
        public int? CodProgColheita { get; set; }
        public DateTime? DataColheita { get; set; }
        public byte[] ControlTs { get; set; }
        public string Controlo { get; set; }
        public int? CodTipoAmostra { get; set; }
        public DateTime? DataHoraColheita { get; set; }
        public string DescrColheitaRtf { get; set; }
        public string Estado { get; set; }
        public DateTime? DataPrevEntrega { get; set; }
        public DateTime? DataPrevEntregaOrig { get; set; }
        public DateTime? DataColheitaOrig { get; set; }
        public int? EntityId { get; set; }
        public int? EntityGroupId { get; set; }
        public int? IdsampleProduct { get; set; }
        public int? ColheitaRelacionada { get; set; }
        public int? RegraDecisao { get; set; }
        public string ExternalRef { get; set; }

        public virtual AmsRelColheitas IdrelColheitaNavigation { get; set; }
        public virtual ICollection<AmsCamposAdicionaisColheitas> AmsCamposAdicionaisColheitas { get; set; }
        public virtual ICollection<AmsColheitaEtiquetas> AmsColheitaEtiquetas { get; set; }
        public virtual ICollection<AmsColheitaParametros> AmsColheitaParametros { get; set; }
    }
}