// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    public partial class AmsCamposAdicionaisColheitas
    {
        public int IdrelColheita { get; set; }
        public int Idcolheita { get; set; }
        public int Sequencia { get; set; }
        public string Valor { get; set; }
        public int? CodParametro { get; set; }
        public string CampoColheita { get; set; }
        public byte[] ControlTs { get; set; }
        public int? CodAtributo { get; set; }
        public string ValorRtf { get; set; }

        public virtual AmsColheitas Id { get; set; }
    }
}