// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    public partial class AmsRelColheitas
    {
        public AmsRelColheitas()
        {
            AmsCamposAdicionaisRelColheita = new HashSet<AmsCamposAdicionaisRelColheita>();
            AmsColheitas = new HashSet<AmsColheitas>();
        }

        public int IdrelColheita { get; set; }
        public string CodCliente { get; set; }
        public DateTime DataColheita { get; set; }
        public string CodResponsavel { get; set; }
        public string TipoColheita { get; set; }
        public string Observacoes { get; set; }
        public byte[] ControlTs { get; set; }
        public int? CodTabPrecos { get; set; }
        public string TipoTabPrecos { get; set; }
        public int? CodUnidade { get; set; }
        public string IdentidadeRequisitante { get; set; }
        public string IdentidadeBoletim { get; set; }
        public string IdentidadeValorizacao { get; set; }
        public string ExternalRef { get; set; }

        public virtual ICollection<AmsCamposAdicionaisRelColheita> AmsCamposAdicionaisRelColheita { get; set; }
        public virtual ICollection<AmsColheitas> AmsColheitas { get; set; }
    }
}