// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    /// <summary>
    /// Detalhe da Guia de Entrega Lista de Vestígios associada
    /// </summary>
    public partial class ForensisguiaEntregaDet
    {
        /// <summary>
        /// ID Guia de Entrega
        /// </summary>
        public int GuiaId { get; set; }
        /// <summary>
        /// ID Vestígio
        /// </summary>
        public int VestigioId { get; set; }
        /// <summary>
        /// Refª do Saco Prova
        /// </summary>
        public string SacoProva { get; set; }

        public virtual ForensisguiaEntrega Guia { get; set; }
        public virtual Forensisvestigio Vestigio { get; set; }
    }
}