// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    /// <summary>
    /// Brigada - da Unidade Requisitante ex: 3ª Brigada
    /// </summary>
    public partial class Forensisbrigada
    {
        public Forensisbrigada()
        {
            Forensisdiligencia = new HashSet<Forensisdiligencia>();
        }

        /// <summary>
        /// ID Brigada (AUTO)
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Descrição ex: 3ª Brigada
        /// </summary>
        public string Descricao { get; set; }
        public string Observacoes { get; set; }

        public virtual ICollection<Forensisdiligencia> Forensisdiligencia { get; set; }
    }
}