// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    /// <summary>
    /// Atividades a Executar Lista de atividades
    /// </summary>
    public partial class Forensisatividade
    {
        /// <summary>
        /// ID Atividade a Executar (AUTO)
        /// </summary>
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Observacoes { get; set; }

        public virtual ForensisatividadeDilig ForensisatividadeDilig { get; set; }
    }
}