// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    /// <summary>
    /// Recolha de Vestígios - Local do Crime
    /// </summary>
    public partial class Forensisrecolha
    {
        /// <summary>
        /// ID Pedido de diligência
        /// </summary>
        public int DiligId { get; set; }
        /// <summary>
        /// Local/Morada/Veículo Local detalhado
        /// </summary>
        public string Local { get; set; }
        /// <summary>
        /// Localização GPS da Recolha
        /// </summary>
        public string LocalGps { get; set; }
        /// <summary>
        /// Data/Hora da Recolha
        /// </summary>
        public DateTime DtRecolha { get; set; }
        /// <summary>
        /// Notas / observações
        /// </summary>
        public string Notas { get; set; }
        /// <summary>
        /// Croqui/Esboço/Imagem   Guardamos aqui a imagem de fundo escolhida + as anotações por cima dessa imagem efetuadas pelo utilizador
        /// </summary>
        public byte[] Croqui { get; set; }

        public virtual Forensisdiligencia Dilig { get; set; }
    }
}