// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    /// <summary>
    /// Regime da Diligência  Classificador para análise estatística
    /// </summary>
    public partial class ForensisregimeDiligencia
    {
        public ForensisregimeDiligencia()
        {
            Forensisdiligencia = new HashSet<Forensisdiligencia>();
        }

        /// <summary>
        /// ID Regime da Diligência (AUTO)
        /// </summary>
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Observacoes { get; set; }

        public virtual ICollection<Forensisdiligencia> Forensisdiligencia { get; set; }
    }
}