// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    /// <summary>
    /// Equipa do Local do Crime  Lista de Peritos que compõem uma equipa para a intervenção no Local do Crime  Terá que haver pelo menos 1 perito na equipa SLC e 1 responsável pelo relatório
    /// </summary>
    public partial class ForensisequipaSlc
    {
        public ForensisequipaSlc()
        {
            Forensisvestigio = new HashSet<Forensisvestigio>();
        }

        /// <summary>
        /// ID Pedido de diligência
        /// </summary>
        public int DiligId { get; set; }
        /// <summary>
        /// ID do Perito (Colaborador)
        /// </summary>
        public int PeritoId { get; set; }
        /// <summary>
        /// Responsável pela elaboração do relatório 1/0
        /// </summary>
        public bool RespRelatorio { get; set; }

        public virtual Forensisdiligencia Dilig { get; set; }
        public virtual ICollection<Forensisvestigio> Forensisvestigio { get; set; }
    }
}