// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace GraphQl.Entities
{
    /// <summary>
    /// Pedido de Diligência - Local do Crime  Pedido de Diligência / Intervenção
    /// </summary>
    public partial class Forensisdiligencia
    {
        public Forensisdiligencia()
        {
            ForensisatividadeDilig = new HashSet<ForensisatividadeDilig>();
            ForensisequipaSlc = new HashSet<ForensisequipaSlc>();
            ForensisguiaEntrega = new HashSet<ForensisguiaEntrega>();
            Forensisvestigio = new HashSet<Forensisvestigio>();
        }

        /// <summary>
        /// ID do Pedido de diligencia Nr. automático - &lt;nº sequencial&gt;  Numerador ModConfig
        /// </summary>
        public int Id { get; set; }
        public string Nuipc { get; set; }
        /// <summary>
        /// Unidade/Entidade Requisitante Lista tabelada
        /// </summary>
        public int EntidadeId { get; set; }
        /// <summary>
        /// Secção da Entidade Requisitante (Tabela EntMoradas) ex.: 1ª Secção
        /// </summary>
        public short? SeccaoId { get; set; }
        /// <summary>
        /// Brigada da Entidade Requisitante Lista tabelada ex: 3ª Brigada
        /// </summary>
        public int? BrigadaId { get; set; }
        /// <summary>
        /// Categoria do inspetor responsável Lista tabelada
        /// </summary>
        public int CatInspetorId { get; set; }
        /// <summary>
        /// Nomde do inspetor responsável, no local do crime
        /// </summary>
        public string Inspetor { get; set; }
        /// <summary>
        /// Assinatura do inspetor responsável (Imagem digitalizada)
        /// </summary>
        public byte[] RubricaInspetor { get; set; }
        /// <summary>
        /// Data/Hora da diligência (Pedido de Intervenção)
        /// </summary>
        public DateTime DtDiligencia { get; set; }
        /// <summary>
        /// Data/Hora da ocorrência dos fatos
        /// </summary>
        public DateTime? DtFatos { get; set; }
        /// <summary>
        /// ID do Âmbito da diligência
        /// </summary>
        public int AmbitoId { get; set; }
        /// <summary>
        /// Local da ocorrência
        /// </summary>
        public string Local { get; set; }
        /// <summary>
        /// Outras informações
        /// </summary>
        public string Info { get; set; }
        /// <summary>
        /// ID da Unidade Laboratorial Carregado com a UL  do Utilizador/Colaborador que regista a diligência  Usado para separar os dados de cada UL 
        /// </summary>
        public int UnidadeLabId { get; set; }
        /// <summary>
        /// ID Regime da Diligência
        /// </summary>
        public int RegimeDiligId { get; set; }

        public virtual ForensisambitoDiligencia Ambito { get; set; }
        public virtual Forensisbrigada Brigada { get; set; }
        public virtual ForensiscatInspetor CatInspetor { get; set; }
        public virtual ForensisregimeDiligencia RegimeDilig { get; set; }
        public virtual Forensisrecolha Forensisrecolha { get; set; }
        public virtual ICollection<ForensisatividadeDilig> ForensisatividadeDilig { get; set; }
        public virtual ICollection<ForensisequipaSlc> ForensisequipaSlc { get; set; }
        public virtual ICollection<ForensisguiaEntrega> ForensisguiaEntrega { get; set; }
        public virtual ICollection<Forensisvestigio> Forensisvestigio { get; set; }
    }
}